# [[map]]
# UUID = "67E3-17ED"
# mount_point = "/data2"
# readonly = true
[[map]]
UUID = "5D35-AA1B"
mount_point = "/data3"
# readonly = true
[[map]]
UUID = "5D82-28DD"
mount_point = "/mount/Book"
# readonly = true
[[map]]
UUID = "825294B65294B101"
mount_point = "/mount/replaceable"
# readonly = true

[[actions.mount]]
cmd='sudo'
params=["docker", "restart", "rpi-samba"]
[[actions.mount]]
cmd='sudo'
params=["sync"]
[[actions.umount]]


